global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "redis_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'redis_exporter:9121' ]
  - job_name: "mongodb_exporter_pod"
    static_configs:
      - targets: [ 'mongodb_exporter:9216' ]