// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: court.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CourtDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decorations map[int32]bool `protobuf:"bytes,1,rep,name=decorations,proto3" json:"decorations,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	HasCourt    bool           `protobuf:"varint,2,opt,name=hasCourt,proto3" json:"hasCourt,omitempty"`
}

func (x *CourtDetail) Reset() {
	*x = CourtDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourtDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourtDetail) ProtoMessage() {}

func (x *CourtDetail) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourtDetail.ProtoReflect.Descriptor instead.
func (*CourtDetail) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{0}
}

func (x *CourtDetail) GetDecorations() map[int32]bool {
	if x != nil {
		return x.Decorations
	}
	return nil
}

func (x *CourtDetail) GetHasCourt() bool {
	if x != nil {
		return x.HasCourt
	}
	return false
}

type CourtInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chips  map[int32]int32        `protobuf:"bytes,1,rep,name=chips,proto3" json:"chips,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Courts map[int32]*CourtDetail `protobuf:"bytes,2,rep,name=courts,proto3" json:"courts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Usage  map[int32]int32        `protobuf:"bytes,3,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *CourtInfo) Reset() {
	*x = CourtInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourtInfo) ProtoMessage() {}

func (x *CourtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourtInfo.ProtoReflect.Descriptor instead.
func (*CourtInfo) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{1}
}

func (x *CourtInfo) GetChips() map[int32]int32 {
	if x != nil {
		return x.Chips
	}
	return nil
}

func (x *CourtInfo) GetCourts() map[int32]*CourtDetail {
	if x != nil {
		return x.Courts
	}
	return nil
}

func (x *CourtInfo) GetUsage() map[int32]int32 {
	if x != nil {
		return x.Usage
	}
	return nil
}

type CourtBuyRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ir   *ItemUpdateResult `protobuf:"bytes,1,opt,name=ir,proto3" json:"ir,omitempty"`
	Info *CourtInfo        `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *CourtBuyRet) Reset() {
	*x = CourtBuyRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourtBuyRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourtBuyRet) ProtoMessage() {}

func (x *CourtBuyRet) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourtBuyRet.ProtoReflect.Descriptor instead.
func (*CourtBuyRet) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{2}
}

func (x *CourtBuyRet) GetIr() *ItemUpdateResult {
	if x != nil {
		return x.Ir
	}
	return nil
}

func (x *CourtBuyRet) GetInfo() *CourtInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CourtDecoratorOpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"` // 球场id
	Did int32 `protobuf:"varint,2,opt,name=did,proto3" json:"did,omitempty"` // 装饰id
}

func (x *CourtDecoratorOpt) Reset() {
	*x = CourtDecoratorOpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourtDecoratorOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourtDecoratorOpt) ProtoMessage() {}

func (x *CourtDecoratorOpt) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourtDecoratorOpt.ProtoReflect.Descriptor instead.
func (*CourtDecoratorOpt) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{3}
}

func (x *CourtDecoratorOpt) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CourtDecoratorOpt) GetDid() int32 {
	if x != nil {
		return x.Did
	}
	return 0
}

type BuyCourtDecoratorOpt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid  int32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`          // 球场id
	Dids []int32 `protobuf:"varint,2,rep,packed,name=dids,proto3" json:"dids,omitempty"` // 装饰id
}

func (x *BuyCourtDecoratorOpt) Reset() {
	*x = BuyCourtDecoratorOpt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyCourtDecoratorOpt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyCourtDecoratorOpt) ProtoMessage() {}

func (x *BuyCourtDecoratorOpt) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyCourtDecoratorOpt.ProtoReflect.Descriptor instead.
func (*BuyCourtDecoratorOpt) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{4}
}

func (x *BuyCourtDecoratorOpt) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *BuyCourtDecoratorOpt) GetDids() []int32 {
	if x != nil {
		return x.Dids
	}
	return nil
}

type CourtChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mod int32 `protobuf:"varint,1,opt,name=mod,proto3" json:"mod,omitempty"`
	Pid int32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *CourtChange) Reset() {
	*x = CourtChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourtChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourtChange) ProtoMessage() {}

func (x *CourtChange) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourtChange.ProtoReflect.Descriptor instead.
func (*CourtChange) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{5}
}

func (x *CourtChange) GetMod() int32 {
	if x != nil {
		return x.Mod
	}
	return 0
}

func (x *CourtChange) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type FillCourtChipReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourtId int32 `protobuf:"varint,1,opt,name=courtId,proto3" json:"courtId,omitempty"` // 球场id
}

func (x *FillCourtChipReq) Reset() {
	*x = FillCourtChipReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_court_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillCourtChipReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillCourtChipReq) ProtoMessage() {}

func (x *FillCourtChipReq) ProtoReflect() protoreflect.Message {
	mi := &file_court_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillCourtChipReq.ProtoReflect.Descriptor instead.
func (*FillCourtChipReq) Descriptor() ([]byte, []int) {
	return file_court_proto_rawDescGZIP(), []int{6}
}

func (x *FillCourtChipReq) GetCourtId() int32 {
	if x != nil {
		return x.CourtId
	}
	return 0
}

var File_court_proto protoreflect.FileDescriptor

var file_court_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x69,
	0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x0b, 0x43, 0x6f,
	0x75, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x3f, 0x0a, 0x0b, 0x64, 0x65, 0x63,
	0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x44, 0x65, 0x63,
	0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x64,
	0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x61,
	0x73, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61,
	0x73, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x1a, 0x3e, 0x0a, 0x10, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd2, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x72, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x43, 0x68, 0x69, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x63, 0x68, 0x69, 0x70,
	0x73, 0x12, 0x2e, 0x0a, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f,
	0x75, 0x72, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x75, 0x72, 0x74,
	0x73, 0x12, 0x2b, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x38,
	0x0a, 0x0a, 0x43, 0x68, 0x69, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x47, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x72,
	0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x43, 0x6f, 0x75, 0x72, 0x74,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x1a, 0x38, 0x0a, 0x0a, 0x55, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x50, 0x0a, 0x0b, 0x43,
	0x6f, 0x75, 0x72, 0x74, 0x42, 0x75, 0x79, 0x52, 0x65, 0x74, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x02, 0x69, 0x72, 0x12, 0x1e, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6f,
	0x75, 0x72, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x37, 0x0a,
	0x11, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4f,
	0x70, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x70, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x14, 0x42, 0x75, 0x79, 0x43, 0x6f, 0x75,
	0x72, 0x74, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4f, 0x70, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04,
	0x64, 0x69, 0x64, 0x73, 0x22, 0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x75, 0x72, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6d, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x6c, 0x43,
	0x6f, 0x75, 0x72, 0x74, 0x43, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x72, 0x74, 0x49, 0x64, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_court_proto_rawDescOnce sync.Once
	file_court_proto_rawDescData = file_court_proto_rawDesc
)

func file_court_proto_rawDescGZIP() []byte {
	file_court_proto_rawDescOnce.Do(func() {
		file_court_proto_rawDescData = protoimpl.X.CompressGZIP(file_court_proto_rawDescData)
	})
	return file_court_proto_rawDescData
}

var file_court_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_court_proto_goTypes = []interface{}{
	(*CourtDetail)(nil),          // 0: CourtDetail
	(*CourtInfo)(nil),            // 1: CourtInfo
	(*CourtBuyRet)(nil),          // 2: CourtBuyRet
	(*CourtDecoratorOpt)(nil),    // 3: CourtDecoratorOpt
	(*BuyCourtDecoratorOpt)(nil), // 4: BuyCourtDecoratorOpt
	(*CourtChange)(nil),          // 5: CourtChange
	(*FillCourtChipReq)(nil),     // 6: FillCourtChipReq
	nil,                          // 7: CourtDetail.DecorationsEntry
	nil,                          // 8: CourtInfo.ChipsEntry
	nil,                          // 9: CourtInfo.CourtsEntry
	nil,                          // 10: CourtInfo.UsageEntry
	(*ItemUpdateResult)(nil),     // 11: ItemUpdateResult
}
var file_court_proto_depIdxs = []int32{
	7,  // 0: CourtDetail.decorations:type_name -> CourtDetail.DecorationsEntry
	8,  // 1: CourtInfo.chips:type_name -> CourtInfo.ChipsEntry
	9,  // 2: CourtInfo.courts:type_name -> CourtInfo.CourtsEntry
	10, // 3: CourtInfo.usage:type_name -> CourtInfo.UsageEntry
	11, // 4: CourtBuyRet.ir:type_name -> ItemUpdateResult
	1,  // 5: CourtBuyRet.info:type_name -> CourtInfo
	0,  // 6: CourtInfo.CourtsEntry.value:type_name -> CourtDetail
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_court_proto_init() }
func file_court_proto_init() {
	if File_court_proto != nil {
		return
	}
	file_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_court_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourtDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_court_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourtInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_court_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourtBuyRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_court_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourtDecoratorOpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_court_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyCourtDecoratorOpt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_court_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CourtChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_court_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillCourtChipReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_court_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_court_proto_goTypes,
		DependencyIndexes: file_court_proto_depIdxs,
		MessageInfos:      file_court_proto_msgTypes,
	}.Build()
	File_court_proto = out.File
	file_court_proto_rawDesc = nil
	file_court_proto_goTypes = nil
	file_court_proto_depIdxs = nil
}
