// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: extend.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 鉴权类型
type AuthType int32

const (
	AuthType_AuthNone    AuthType = 0 // 无鉴权
	AuthType_AuthUser    AuthType = 1 // 玩家鉴权
	AuthType_AuthManager AuthType = 2 // 内部管理接口
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AuthNone",
		1: "AuthUser",
		2: "AuthManager",
	}
	AuthType_value = map[string]int32{
		"AuthNone":    0,
		"AuthUser":    1,
		"AuthManager": 2,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_extend_proto_enumTypes[0].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_extend_proto_enumTypes[0]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_extend_proto_rawDescGZIP(), []int{0}
}

type ServiceName int32

const (
	ServiceName_ServerNone   ServiceName = 0
	ServiceName_ServerGate   ServiceName = 1
	ServiceName_ServiceLogin ServiceName = 2
	ServiceName_ServiceLogic ServiceName = 3
)

// Enum value maps for ServiceName.
var (
	ServiceName_name = map[int32]string{
		0: "ServerNone",
		1: "ServerGate",
		2: "ServiceLogin",
		3: "ServiceLogic",
	}
	ServiceName_value = map[string]int32{
		"ServerNone":   0,
		"ServerGate":   1,
		"ServiceLogin": 2,
		"ServiceLogic": 3,
	}
)

func (x ServiceName) Enum() *ServiceName {
	p := new(ServiceName)
	*p = x
	return p
}

func (x ServiceName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceName) Descriptor() protoreflect.EnumDescriptor {
	return file_extend_proto_enumTypes[1].Descriptor()
}

func (ServiceName) Type() protoreflect.EnumType {
	return &file_extend_proto_enumTypes[1]
}

func (x ServiceName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceName.Descriptor instead.
func (ServiceName) EnumDescriptor() ([]byte, []int) {
	return file_extend_proto_rawDescGZIP(), []int{1}
}

type ProtoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*ProtoIdRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *ProtoId) Reset() {
	*x = ProtoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoId) ProtoMessage() {}

func (x *ProtoId) ProtoReflect() protoreflect.Message {
	mi := &file_extend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoId.ProtoReflect.Descriptor instead.
func (*ProtoId) Descriptor() ([]byte, []int) {
	return file_extend_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoId) GetRules() []*ProtoIdRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ProtoIdRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd CMD `protobuf:"varint,1,opt,name=cmd,proto3,enum=CMD" json:"cmd,omitempty"`
}

func (x *ProtoIdRule) Reset() {
	*x = ProtoIdRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_extend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoIdRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoIdRule) ProtoMessage() {}

func (x *ProtoIdRule) ProtoReflect() protoreflect.Message {
	mi := &file_extend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoIdRule.ProtoReflect.Descriptor instead.
func (*ProtoIdRule) Descriptor() ([]byte, []int) {
	return file_extend_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoIdRule) GetCmd() CMD {
	if x != nil {
		return x.Cmd
	}
	return CMD_INVALID
}

var file_extend_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*ProtoIdRule)(nil),
		Field:         1001,
		Name:          "extend.id",
		Tag:           "bytes,1001,opt,name=id",
		Filename:      "extend.proto",
	},
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*AuthType)(nil),
		Field:         1002,
		Name:          "extend.auth_method",
		Tag:           "varint,1002,opt,name=auth_method,enum=extend.AuthType",
		Filename:      "extend.proto",
	},
	{
		ExtendedType:  (*descriptor.ServiceOptions)(nil),
		ExtensionType: (*AuthType)(nil),
		Field:         1002,
		Name:          "extend.auth_service",
		Tag:           "varint,1002,opt,name=auth_service,enum=extend.AuthType",
		Filename:      "extend.proto",
	},
	{
		ExtendedType:  (*descriptor.ServiceOptions)(nil),
		ExtensionType: (*ServiceName)(nil),
		Field:         1004,
		Name:          "extend.service_name",
		Tag:           "varint,1004,opt,name=service_name,enum=extend.ServiceName",
		Filename:      "extend.proto",
	},
}

// Extension fields to descriptor.MethodOptions.
var (
	// See `ProtoIdRule`
	//
	// optional extend.ProtoIdRule id = 1001;
	E_Id = &file_extend_proto_extTypes[0]
	// 若 auth_method 定义则优先使用，否则使用 service 的定义
	//
	// optional extend.AuthType auth_method = 1002;
	E_AuthMethod = &file_extend_proto_extTypes[1]
)

// Extension fields to descriptor.ServiceOptions.
var (
	// optional extend.AuthType auth_service = 1002;
	E_AuthService = &file_extend_proto_extTypes[2]
	// optional extend.ServiceName service_name = 1004;
	E_ServiceName = &file_extend_proto_extTypes[3]
)

var File_extend_proto protoreflect.FileDescriptor

var file_extend_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x1a, 0x09, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x29,
	0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x52, 0x75,
	0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x04, 0x2e, 0x43, 0x4d, 0x44, 0x52, 0x03, 0x63, 0x6d, 0x64,
	0x2a, 0x37, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x41, 0x75, 0x74, 0x68, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x75,
	0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x10, 0x02, 0x2a, 0x51, 0x0a, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x47, 0x61, 0x74, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x63, 0x10, 0x03, 0x3a, 0x44, 0x0a, 0x02,
	0x69, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xe9, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65, 0x78, 0x74, 0x65,
	0x6e, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x02,
	0x69, 0x64, 0x3a, 0x52, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xea, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x55, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xea, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3a, 0x58, 0x0a,
	0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xec,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_extend_proto_rawDescOnce sync.Once
	file_extend_proto_rawDescData = file_extend_proto_rawDesc
)

func file_extend_proto_rawDescGZIP() []byte {
	file_extend_proto_rawDescOnce.Do(func() {
		file_extend_proto_rawDescData = protoimpl.X.CompressGZIP(file_extend_proto_rawDescData)
	})
	return file_extend_proto_rawDescData
}

var file_extend_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_extend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_extend_proto_goTypes = []interface{}{
	(AuthType)(0),                     // 0: extend.AuthType
	(ServiceName)(0),                  // 1: extend.ServiceName
	(*ProtoId)(nil),                   // 2: extend.ProtoId
	(*ProtoIdRule)(nil),               // 3: extend.ProtoIdRule
	(CMD)(0),                          // 4: CMD
	(*descriptor.MethodOptions)(nil),  // 5: google.protobuf.MethodOptions
	(*descriptor.ServiceOptions)(nil), // 6: google.protobuf.ServiceOptions
}
var file_extend_proto_depIdxs = []int32{
	3,  // 0: extend.ProtoId.rules:type_name -> extend.ProtoIdRule
	4,  // 1: extend.ProtoIdRule.cmd:type_name -> CMD
	5,  // 2: extend.id:extendee -> google.protobuf.MethodOptions
	5,  // 3: extend.auth_method:extendee -> google.protobuf.MethodOptions
	6,  // 4: extend.auth_service:extendee -> google.protobuf.ServiceOptions
	6,  // 5: extend.service_name:extendee -> google.protobuf.ServiceOptions
	3,  // 6: extend.id:type_name -> extend.ProtoIdRule
	0,  // 7: extend.auth_method:type_name -> extend.AuthType
	0,  // 8: extend.auth_service:type_name -> extend.AuthType
	1,  // 9: extend.service_name:type_name -> extend.ServiceName
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	6,  // [6:10] is the sub-list for extension type_name
	2,  // [2:6] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_extend_proto_init() }
func file_extend_proto_init() {
	if File_extend_proto != nil {
		return
	}
	file_cmd_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_extend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_extend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoIdRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_extend_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_extend_proto_goTypes,
		DependencyIndexes: file_extend_proto_depIdxs,
		EnumInfos:         file_extend_proto_enumTypes,
		MessageInfos:      file_extend_proto_msgTypes,
		ExtensionInfos:    file_extend_proto_extTypes,
	}.Build()
	File_extend_proto = out.File
	file_extend_proto_rawDesc = nil
	file_extend_proto_goTypes = nil
	file_extend_proto_depIdxs = nil
}
