// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: invite.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type INVITE_REWARD_STATUS int32

const (
	INVITE_REWARD_STATUS_CANT_REWARD    INVITE_REWARD_STATUS = 0 // 不可领取
	INVITE_REWARD_STATUS_CAN_REWARD     INVITE_REWARD_STATUS = 1 // 可领取
	INVITE_REWARD_STATUS_ALREADY_REWARD INVITE_REWARD_STATUS = 2 // 已领取
)

// Enum value maps for INVITE_REWARD_STATUS.
var (
	INVITE_REWARD_STATUS_name = map[int32]string{
		0: "CANT_REWARD",
		1: "CAN_REWARD",
		2: "ALREADY_REWARD",
	}
	INVITE_REWARD_STATUS_value = map[string]int32{
		"CANT_REWARD":    0,
		"CAN_REWARD":     1,
		"ALREADY_REWARD": 2,
	}
)

func (x INVITE_REWARD_STATUS) Enum() *INVITE_REWARD_STATUS {
	p := new(INVITE_REWARD_STATUS)
	*p = x
	return p
}

func (x INVITE_REWARD_STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (INVITE_REWARD_STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_invite_proto_enumTypes[0].Descriptor()
}

func (INVITE_REWARD_STATUS) Type() protoreflect.EnumType {
	return &file_invite_proto_enumTypes[0]
}

func (x INVITE_REWARD_STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use INVITE_REWARD_STATUS.Descriptor instead.
func (INVITE_REWARD_STATUS) EnumDescriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{0}
}

type PushInviteMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeInvitePlayerIc uint64 `protobuf:"varint,1,opt,name=BeInvitePlayerIc,proto3" json:"BeInvitePlayerIc,omitempty"` // 被邀请玩家ic
	InvitePlayerIc   uint64 `protobuf:"varint,2,opt,name=InvitePlayerIc,proto3" json:"InvitePlayerIc,omitempty"`     // 邀请玩家ic
}

func (x *PushInviteMsg) Reset() {
	*x = PushInviteMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushInviteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushInviteMsg) ProtoMessage() {}

func (x *PushInviteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushInviteMsg.ProtoReflect.Descriptor instead.
func (*PushInviteMsg) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{0}
}

func (x *PushInviteMsg) GetBeInvitePlayerIc() uint64 {
	if x != nil {
		return x.BeInvitePlayerIc
	}
	return 0
}

func (x *PushInviteMsg) GetInvitePlayerIc() uint64 {
	if x != nil {
		return x.InvitePlayerIc
	}
	return 0
}

// 玩家邀请信息
type InviteInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Received           []int32              `protobuf:"varint,1,rep,packed,name=received,proto3" json:"received,omitempty"`                                        // 已领取的奖励index,对应表中index
	Ic                 []uint64             `protobuf:"varint,2,rep,packed,name=ic,proto3" json:"ic,omitempty"`                                                    // 已接受邀请的玩家的ic
	MaxLevelReward     int32                `protobuf:"varint,3,opt,name=maxLevelReward,proto3" json:"maxLevelReward,omitempty"`                                   // 满级奖励可领取数量
	InviteRewardStatus INVITE_REWARD_STATUS `protobuf:"varint,4,opt,name=inviteRewardStatus,proto3,enum=INVITE_REWARD_STATUS" json:"inviteRewardStatus,omitempty"` // 被邀请者奖励领取状态 [0]不可领取[1]可领取[2]已领取
}

func (x *InviteInfo) Reset() {
	*x = InviteInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteInfo) ProtoMessage() {}

func (x *InviteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteInfo.ProtoReflect.Descriptor instead.
func (*InviteInfo) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{1}
}

func (x *InviteInfo) GetReceived() []int32 {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *InviteInfo) GetIc() []uint64 {
	if x != nil {
		return x.Ic
	}
	return nil
}

func (x *InviteInfo) GetMaxLevelReward() int32 {
	if x != nil {
		return x.MaxLevelReward
	}
	return 0
}

func (x *InviteInfo) GetInviteRewardStatus() INVITE_REWARD_STATUS {
	if x != nil {
		return x.InviteRewardStatus
	}
	return INVITE_REWARD_STATUS_CANT_REWARD
}

// 领取邀请奖励
type InviteRewardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`   // 奖励index,对应表中index,传0表示领取满级奖励,传-1表示领取被邀请者奖励
	Param1 uint32 `protobuf:"varint,2,opt,name=param1,proto3" json:"param1,omitempty"` // 如果领取的是未指定球员的熟练度则表示目标球员id
}

func (x *InviteRewardReq) Reset() {
	*x = InviteRewardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteRewardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRewardReq) ProtoMessage() {}

func (x *InviteRewardReq) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRewardReq.ProtoReflect.Descriptor instead.
func (*InviteRewardReq) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{2}
}

func (x *InviteRewardReq) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InviteRewardReq) GetParam1() uint32 {
	if x != nil {
		return x.Param1
	}
	return 0
}

// 领取邀请奖励返回
type InviteRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *InviteInfo       `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Item *ItemUpdateResult `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *InviteRewardResp) Reset() {
	*x = InviteRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRewardResp) ProtoMessage() {}

func (x *InviteRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRewardResp.ProtoReflect.Descriptor instead.
func (*InviteRewardResp) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{3}
}

func (x *InviteRewardResp) GetInfo() *InviteInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *InviteRewardResp) GetItem() *ItemUpdateResult {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_invite_proto protoreflect.FileDescriptor

var file_invite_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0d, 0x50, 0x75,
	0x73, 0x68, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x10, 0x42,
	0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x42, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x63, 0x22,
	0xa7, 0x01, 0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x63,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x02, 0x69, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61,
	0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x12, 0x45, 0x0a, 0x12, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x49, 0x4e, 0x56, 0x49, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x52, 0x12, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x31, 0x22, 0x5a, 0x0a, 0x10, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12,
	0x25, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x2a, 0x4b, 0x0a, 0x14, 0x49, 0x4e, 0x56, 0x49, 0x54, 0x45,
	0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0f,
	0x0a, 0x0b, 0x43, 0x41, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x41, 0x4e, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52,
	0x44, 0x10, 0x02, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_invite_proto_rawDescOnce sync.Once
	file_invite_proto_rawDescData = file_invite_proto_rawDesc
)

func file_invite_proto_rawDescGZIP() []byte {
	file_invite_proto_rawDescOnce.Do(func() {
		file_invite_proto_rawDescData = protoimpl.X.CompressGZIP(file_invite_proto_rawDescData)
	})
	return file_invite_proto_rawDescData
}

var file_invite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_invite_proto_goTypes = []interface{}{
	(INVITE_REWARD_STATUS)(0), // 0: INVITE_REWARD_STATUS
	(*PushInviteMsg)(nil),     // 1: PushInviteMsg
	(*InviteInfo)(nil),        // 2: InviteInfo
	(*InviteRewardReq)(nil),   // 3: InviteRewardReq
	(*InviteRewardResp)(nil),  // 4: InviteRewardResp
	(*ItemUpdateResult)(nil),  // 5: ItemUpdateResult
}
var file_invite_proto_depIdxs = []int32{
	0, // 0: InviteInfo.inviteRewardStatus:type_name -> INVITE_REWARD_STATUS
	2, // 1: InviteRewardResp.info:type_name -> InviteInfo
	5, // 2: InviteRewardResp.item:type_name -> ItemUpdateResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_invite_proto_init() }
func file_invite_proto_init() {
	if File_invite_proto != nil {
		return
	}
	file_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_invite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushInviteMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteRewardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_invite_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invite_proto_goTypes,
		DependencyIndexes: file_invite_proto_depIdxs,
		EnumInfos:         file_invite_proto_enumTypes,
		MessageInfos:      file_invite_proto_msgTypes,
	}.Build()
	File_invite_proto = out.File
	file_invite_proto_rawDesc = nil
	file_invite_proto_goTypes = nil
	file_invite_proto_depIdxs = nil
}
