// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: manage.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WhiteListOpt int32

const (
	WhiteListOpt_Default  WhiteListOpt = 0
	WhiteListOpt_Add      WhiteListOpt = 1 // 添加
	WhiteListOpt_Del      WhiteListOpt = 2 // 删除
	WhiteListOpt_ClearIc  WhiteListOpt = 3 // 清除ic列表
	WhiteListOpt_ClearIp  WhiteListOpt = 4 // 清除ip列表
	WhiteListOpt_ClearAll WhiteListOpt = 5 // 清除所有
)

// Enum value maps for WhiteListOpt.
var (
	WhiteListOpt_name = map[int32]string{
		0: "Default",
		1: "Add",
		2: "Del",
		3: "ClearIc",
		4: "ClearIp",
		5: "ClearAll",
	}
	WhiteListOpt_value = map[string]int32{
		"Default":  0,
		"Add":      1,
		"Del":      2,
		"ClearIc":  3,
		"ClearIp":  4,
		"ClearAll": 5,
	}
)

func (x WhiteListOpt) Enum() *WhiteListOpt {
	p := new(WhiteListOpt)
	*p = x
	return p
}

func (x WhiteListOpt) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WhiteListOpt) Descriptor() protoreflect.EnumDescriptor {
	return file_manage_proto_enumTypes[0].Descriptor()
}

func (WhiteListOpt) Type() protoreflect.EnumType {
	return &file_manage_proto_enumTypes[0]
}

func (x WhiteListOpt) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WhiteListOpt.Descriptor instead.
func (WhiteListOpt) EnumDescriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{0}
}

type GenTokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 鉴权 token
	Uid   uint64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`    // uid
}

func (x *GenTokenResp) Reset() {
	*x = GenTokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenTokenResp) ProtoMessage() {}

func (x *GenTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenTokenResp.ProtoReflect.Descriptor instead.
func (*GenTokenResp) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{0}
}

func (x *GenTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenTokenResp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type StringStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	S string `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
}

func (x *StringStruct) Reset() {
	*x = StringStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringStruct) ProtoMessage() {}

func (x *StringStruct) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringStruct.ProtoReflect.Descriptor instead.
func (*StringStruct) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{1}
}

func (x *StringStruct) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

type SendMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsGlobal        bool             `protobuf:"varint,1,opt,name=isGlobal,proto3" json:"isGlobal,omitempty"`
	MultiInviteCode []uint64         `protobuf:"varint,2,rep,packed,name=multiInviteCode,proto3" json:"multiInviteCode,omitempty"`
	Reward          []*ItemCommon    `protobuf:"bytes,3,rep,name=reward,proto3" json:"reward,omitempty"`
	ClientMailId    int32            `protobuf:"varint,4,opt,name=clientMailId,proto3" json:"clientMailId,omitempty"`
	BindKey         string           `protobuf:"bytes,5,opt,name=bindKey,proto3" json:"bindKey,omitempty"`
	Containers      []*MailContainer `protobuf:"bytes,6,rep,name=containers,proto3" json:"containers,omitempty"`
	Platform        int32            `protobuf:"varint,7,opt,name=platform,proto3" json:"platform,omitempty"`
	StartAt         string           `protobuf:"bytes,8,opt,name=startAt,proto3" json:"startAt,omitempty"` // 开始时间之后注册的账号可以收到全局邮件
	EndAt           string           `protobuf:"bytes,9,opt,name=endAt,proto3" json:"endAt,omitempty"`     // 结束时间之前注册的账号可以收到全局邮件
}

func (x *SendMailReq) Reset() {
	*x = SendMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailReq) ProtoMessage() {}

func (x *SendMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailReq.ProtoReflect.Descriptor instead.
func (*SendMailReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{2}
}

func (x *SendMailReq) GetIsGlobal() bool {
	if x != nil {
		return x.IsGlobal
	}
	return false
}

func (x *SendMailReq) GetMultiInviteCode() []uint64 {
	if x != nil {
		return x.MultiInviteCode
	}
	return nil
}

func (x *SendMailReq) GetReward() []*ItemCommon {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *SendMailReq) GetClientMailId() int32 {
	if x != nil {
		return x.ClientMailId
	}
	return 0
}

func (x *SendMailReq) GetBindKey() string {
	if x != nil {
		return x.BindKey
	}
	return ""
}

func (x *SendMailReq) GetContainers() []*MailContainer {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *SendMailReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *SendMailReq) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *SendMailReq) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type GenerateActiveCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num      int32  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`          // 生成个数
	StartAt  string `protobuf:"bytes,2,opt,name=startAt,proto3" json:"startAt,omitempty"`   // 启用时间
	ExpireAt string `protobuf:"bytes,3,opt,name=expireAt,proto3" json:"expireAt,omitempty"` // 废弃时间
	GroupId  int32  `protobuf:"varint,4,opt,name=groupId,proto3" json:"groupId,omitempty"`  // 生成批次
}

func (x *GenerateActiveCode) Reset() {
	*x = GenerateActiveCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateActiveCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateActiveCode) ProtoMessage() {}

func (x *GenerateActiveCode) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateActiveCode.ProtoReflect.Descriptor instead.
func (*GenerateActiveCode) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateActiveCode) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GenerateActiveCode) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *GenerateActiveCode) GetExpireAt() string {
	if x != nil {
		return x.ExpireAt
	}
	return ""
}

func (x *GenerateActiveCode) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// mjp获取激活码
type GetActiveCodeMJP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId string `protobuf:"bytes,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"` // mjp公众号服务器获取的唯一id，微信绑定
	GroupId  int32  `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`  // 批次
}

func (x *GetActiveCodeMJP) Reset() {
	*x = GetActiveCodeMJP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveCodeMJP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveCodeMJP) ProtoMessage() {}

func (x *GetActiveCodeMJP) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveCodeMJP.ProtoReflect.Descriptor instead.
func (*GetActiveCodeMJP) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{4}
}

func (x *GetActiveCodeMJP) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *GetActiveCodeMJP) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 返回给mjp一条激活码
type GetActiveCodeMJPRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActivateCode string `protobuf:"bytes,1,opt,name=activateCode,proto3" json:"activateCode,omitempty"`
}

func (x *GetActiveCodeMJPRet) Reset() {
	*x = GetActiveCodeMJPRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveCodeMJPRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveCodeMJPRet) ProtoMessage() {}

func (x *GetActiveCodeMJPRet) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveCodeMJPRet.ProtoReflect.Descriptor instead.
func (*GetActiveCodeMJPRet) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{5}
}

func (x *GetActiveCodeMJPRet) GetActivateCode() string {
	if x != nil {
		return x.ActivateCode
	}
	return ""
}

type GetWechatCDKeyMjp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId string `protobuf:"bytes,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
}

func (x *GetWechatCDKeyMjp) Reset() {
	*x = GetWechatCDKeyMjp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWechatCDKeyMjp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWechatCDKeyMjp) ProtoMessage() {}

func (x *GetWechatCDKeyMjp) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWechatCDKeyMjp.ProtoReflect.Descriptor instead.
func (*GetWechatCDKeyMjp) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{6}
}

func (x *GetWechatCDKeyMjp) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

type WechatCDKeyMjpRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CdKey string `protobuf:"bytes,1,opt,name=cdKey,proto3" json:"cdKey,omitempty"`
}

func (x *WechatCDKeyMjpRet) Reset() {
	*x = WechatCDKeyMjpRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WechatCDKeyMjpRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WechatCDKeyMjpRet) ProtoMessage() {}

func (x *WechatCDKeyMjpRet) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WechatCDKeyMjpRet.ProtoReflect.Descriptor instead.
func (*WechatCDKeyMjpRet) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{7}
}

func (x *WechatCDKeyMjpRet) GetCdKey() string {
	if x != nil {
		return x.CdKey
	}
	return ""
}

type SetPublicCDKeyTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start string `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End   string `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *SetPublicCDKeyTime) Reset() {
	*x = SetPublicCDKeyTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPublicCDKeyTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPublicCDKeyTime) ProtoMessage() {}

func (x *SetPublicCDKeyTime) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPublicCDKeyTime.ProtoReflect.Descriptor instead.
func (*SetPublicCDKeyTime) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{8}
}

func (x *SetPublicCDKeyTime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetPublicCDKeyTime) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *SetPublicCDKeyTime) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

type PublicCDKeyRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pcdk map[string]string `protobuf:"bytes,1,rep,name=pcdk,proto3" json:"pcdk,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PublicCDKeyRet) Reset() {
	*x = PublicCDKeyRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicCDKeyRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicCDKeyRet) ProtoMessage() {}

func (x *PublicCDKeyRet) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicCDKeyRet.ProtoReflect.Descriptor instead.
func (*PublicCDKeyRet) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{9}
}

func (x *PublicCDKeyRet) GetPcdk() map[string]string {
	if x != nil {
		return x.Pcdk
	}
	return nil
}

type CDKeyReward struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reward string `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (x *CDKeyReward) Reset() {
	*x = CDKeyReward{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CDKeyReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDKeyReward) ProtoMessage() {}

func (x *CDKeyReward) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDKeyReward.ProtoReflect.Descriptor instead.
func (*CDKeyReward) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{10}
}

func (x *CDKeyReward) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CDKeyReward) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

type CustomizationCodeSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reward  string `protobuf:"bytes,2,opt,name=reward,proto3" json:"reward,omitempty"`
	StartAt string `protobuf:"bytes,3,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt   string `protobuf:"bytes,4,opt,name=endAt,proto3" json:"endAt,omitempty"`
}

func (x *CustomizationCodeSet) Reset() {
	*x = CustomizationCodeSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomizationCodeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomizationCodeSet) ProtoMessage() {}

func (x *CustomizationCodeSet) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomizationCodeSet.ProtoReflect.Descriptor instead.
func (*CustomizationCodeSet) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{11}
}

func (x *CustomizationCodeSet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomizationCodeSet) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

func (x *CustomizationCodeSet) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *CustomizationCodeSet) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type PersonalCDKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId     string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Num         int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartAt     string `protobuf:"bytes,4,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt       string `protobuf:"bytes,5,opt,name=endAt,proto3" json:"endAt,omitempty"`
}

func (x *PersonalCDKey) Reset() {
	*x = PersonalCDKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalCDKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalCDKey) ProtoMessage() {}

func (x *PersonalCDKey) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalCDKey.ProtoReflect.Descriptor instead.
func (*PersonalCDKey) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{12}
}

func (x *PersonalCDKey) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *PersonalCDKey) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *PersonalCDKey) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PersonalCDKey) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *PersonalCDKey) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

type SetActorOutPutStatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeShow   string `protobuf:"bytes,2,opt,name=timeShow,proto3" json:"timeShow,omitempty"`
	TimeOutput string `protobuf:"bytes,3,opt,name=timeOutput,proto3" json:"timeOutput,omitempty"`
	TimeUnable string `protobuf:"bytes,4,opt,name=timeUnable,proto3" json:"timeUnable,omitempty"`
}

func (x *SetActorOutPutStatusReq) Reset() {
	*x = SetActorOutPutStatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetActorOutPutStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActorOutPutStatusReq) ProtoMessage() {}

func (x *SetActorOutPutStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActorOutPutStatusReq.ProtoReflect.Descriptor instead.
func (*SetActorOutPutStatusReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{13}
}

func (x *SetActorOutPutStatusReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetActorOutPutStatusReq) GetTimeShow() string {
	if x != nil {
		return x.TimeShow
	}
	return ""
}

func (x *SetActorOutPutStatusReq) GetTimeOutput() string {
	if x != nil {
		return x.TimeOutput
	}
	return ""
}

func (x *SetActorOutPutStatusReq) GetTimeUnable() string {
	if x != nil {
		return x.TimeUnable
	}
	return ""
}

type VersionCheckPublic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform      int32  `protobuf:"varint,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel       string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	IsWhiteList   bool   `protobuf:"varint,3,opt,name=isWhiteList,proto3" json:"isWhiteList,omitempty"`
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	HUrl          string `protobuf:"bytes,5,opt,name=hUrl,proto3" json:"hUrl,omitempty"`
	FUrl          string `protobuf:"bytes,6,opt,name=fUrl,proto3" json:"fUrl,omitempty"`
	SName         string `protobuf:"bytes,7,opt,name=sName,proto3" json:"sName,omitempty"`
	Open          bool   `protobuf:"varint,8,opt,name=open,proto3" json:"open,omitempty"`
	Note          string `protobuf:"bytes,9,opt,name=note,proto3" json:"note,omitempty"`
	LowestVersion string `protobuf:"bytes,10,opt,name=lowestVersion,proto3" json:"lowestVersion,omitempty"`
}

func (x *VersionCheckPublic) Reset() {
	*x = VersionCheckPublic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionCheckPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionCheckPublic) ProtoMessage() {}

func (x *VersionCheckPublic) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionCheckPublic.ProtoReflect.Descriptor instead.
func (*VersionCheckPublic) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{14}
}

func (x *VersionCheckPublic) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *VersionCheckPublic) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *VersionCheckPublic) GetIsWhiteList() bool {
	if x != nil {
		return x.IsWhiteList
	}
	return false
}

func (x *VersionCheckPublic) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionCheckPublic) GetHUrl() string {
	if x != nil {
		return x.HUrl
	}
	return ""
}

func (x *VersionCheckPublic) GetFUrl() string {
	if x != nil {
		return x.FUrl
	}
	return ""
}

func (x *VersionCheckPublic) GetSName() string {
	if x != nil {
		return x.SName
	}
	return ""
}

func (x *VersionCheckPublic) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *VersionCheckPublic) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *VersionCheckPublic) GetLowestVersion() string {
	if x != nil {
		return x.LowestVersion
	}
	return ""
}

type ChangeWhiteList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform int32        `protobuf:"varint,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel  string       `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Opt      WhiteListOpt `protobuf:"varint,3,opt,name=opt,proto3,enum=WhiteListOpt" json:"opt,omitempty"` // 操作
	Ic       uint64       `protobuf:"varint,4,opt,name=ic,proto3" json:"ic,omitempty"`                     // invite code
	Ip       string       `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`                      // ip
}

func (x *ChangeWhiteList) Reset() {
	*x = ChangeWhiteList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeWhiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeWhiteList) ProtoMessage() {}

func (x *ChangeWhiteList) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeWhiteList.ProtoReflect.Descriptor instead.
func (*ChangeWhiteList) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{15}
}

func (x *ChangeWhiteList) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *ChangeWhiteList) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChangeWhiteList) GetOpt() WhiteListOpt {
	if x != nil {
		return x.Opt
	}
	return WhiteListOpt_Default
}

func (x *ChangeWhiteList) GetIc() uint64 {
	if x != nil {
		return x.Ic
	}
	return 0
}

func (x *ChangeWhiteList) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type PersonalGroupItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Des       string `protobuf:"bytes,1,opt,name=des,proto3" json:"des,omitempty"`              // 描述
	Available int32  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"` // 可用个数
}

func (x *PersonalGroupItem) Reset() {
	*x = PersonalGroupItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalGroupItem) ProtoMessage() {}

func (x *PersonalGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalGroupItem.ProtoReflect.Descriptor instead.
func (*PersonalGroupItem) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{16}
}

func (x *PersonalGroupItem) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *PersonalGroupItem) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type PersonalGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups map[string]*PersonalGroupItem `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // groupId:description
}

func (x *PersonalGroupInfo) Reset() {
	*x = PersonalGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalGroupInfo) ProtoMessage() {}

func (x *PersonalGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalGroupInfo.ProtoReflect.Descriptor instead.
func (*PersonalGroupInfo) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{17}
}

func (x *PersonalGroupInfo) GetGroups() map[string]*PersonalGroupItem {
	if x != nil {
		return x.Groups
	}
	return nil
}

type AvailableCodesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
}

func (x *AvailableCodesReq) Reset() {
	*x = AvailableCodesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableCodesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCodesReq) ProtoMessage() {}

func (x *AvailableCodesReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCodesReq.ProtoReflect.Descriptor instead.
func (*AvailableCodesReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{18}
}

func (x *AvailableCodesReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type AvailableCodesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Codes []string `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *AvailableCodesResp) Reset() {
	*x = AvailableCodesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableCodesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCodesResp) ProtoMessage() {}

func (x *AvailableCodesResp) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCodesResp.ProtoReflect.Descriptor instead.
func (*AvailableCodesResp) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{19}
}

func (x *AvailableCodesResp) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

type AllVersionAddrAndWL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V []*VersionCheckMongo `protobuf:"bytes,1,rep,name=v,proto3" json:"v,omitempty"`
}

func (x *AllVersionAddrAndWL) Reset() {
	*x = AllVersionAddrAndWL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllVersionAddrAndWL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllVersionAddrAndWL) ProtoMessage() {}

func (x *AllVersionAddrAndWL) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllVersionAddrAndWL.ProtoReflect.Descriptor instead.
func (*AllVersionAddrAndWL) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{20}
}

func (x *AllVersionAddrAndWL) GetV() []*VersionCheckMongo {
	if x != nil {
		return x.V
	}
	return nil
}

type GroupSysNoticeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int32  `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GroupSysNoticeReq) Reset() {
	*x = GroupSysNoticeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupSysNoticeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSysNoticeReq) ProtoMessage() {}

func (x *GroupSysNoticeReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSysNoticeReq.ProtoReflect.Descriptor instead.
func (*GroupSysNoticeReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{21}
}

func (x *GroupSysNoticeReq) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupSysNoticeReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Int32Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ic  uint64 `protobuf:"varint,1,opt,name=ic,proto3" json:"ic,omitempty"`
	Num int32  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *Int32Req) Reset() {
	*x = Int32Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32Req) ProtoMessage() {}

func (x *Int32Req) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32Req.ProtoReflect.Descriptor instead.
func (*Int32Req) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{22}
}

func (x *Int32Req) GetIc() uint64 {
	if x != nil {
		return x.Ic
	}
	return 0
}

func (x *Int32Req) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ImportCDKeySet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid   int32 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Level int32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Mid   int32 `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *ImportCDKeySet) Reset() {
	*x = ImportCDKeySet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportCDKeySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCDKeySet) ProtoMessage() {}

func (x *ImportCDKeySet) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCDKeySet.ProtoReflect.Descriptor instead.
func (*ImportCDKeySet) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{23}
}

func (x *ImportCDKeySet) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ImportCDKeySet) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ImportCDKeySet) GetMid() int32 {
	if x != nil {
		return x.Mid
	}
	return 0
}

type GetAllPublicKeyNewReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetAllPublicKeyNewReq) Reset() {
	*x = GetAllPublicKeyNewReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPublicKeyNewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPublicKeyNewReq) ProtoMessage() {}

func (x *GetAllPublicKeyNewReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPublicKeyNewReq.ProtoReflect.Descriptor instead.
func (*GetAllPublicKeyNewReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{24}
}

func (x *GetAllPublicKeyNewReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AllPublicKeyNewRetSub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	TimeStart string `protobuf:"bytes,2,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	TimeEnd   string `protobuf:"bytes,3,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
}

func (x *AllPublicKeyNewRetSub) Reset() {
	*x = AllPublicKeyNewRetSub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllPublicKeyNewRetSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPublicKeyNewRetSub) ProtoMessage() {}

func (x *AllPublicKeyNewRetSub) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPublicKeyNewRetSub.ProtoReflect.Descriptor instead.
func (*AllPublicKeyNewRetSub) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{25}
}

func (x *AllPublicKeyNewRetSub) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AllPublicKeyNewRetSub) GetTimeStart() string {
	if x != nil {
		return x.TimeStart
	}
	return ""
}

func (x *AllPublicKeyNewRetSub) GetTimeEnd() string {
	if x != nil {
		return x.TimeEnd
	}
	return ""
}

type AllPublicKeyNewRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Codes []*AllPublicKeyNewRetSub `protobuf:"bytes,2,rep,name=codes,proto3" json:"codes,omitempty"`
}

func (x *AllPublicKeyNewRet) Reset() {
	*x = AllPublicKeyNewRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllPublicKeyNewRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPublicKeyNewRet) ProtoMessage() {}

func (x *AllPublicKeyNewRet) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPublicKeyNewRet.ProtoReflect.Descriptor instead.
func (*AllPublicKeyNewRet) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{26}
}

func (x *AllPublicKeyNewRet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AllPublicKeyNewRet) GetCodes() []*AllPublicKeyNewRetSub {
	if x != nil {
		return x.Codes
	}
	return nil
}

type FeedAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ic   int32 `protobuf:"varint,1,opt,name=ic,proto3" json:"ic,omitempty"`     // invite code
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 1 天梯    2 约战
}

func (x *FeedAccountReq) Reset() {
	*x = FeedAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedAccountReq) ProtoMessage() {}

func (x *FeedAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedAccountReq.ProtoReflect.Descriptor instead.
func (*FeedAccountReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{27}
}

func (x *FeedAccountReq) GetIc() int32 {
	if x != nil {
		return x.Ic
	}
	return 0
}

func (x *FeedAccountReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SetMissionPrefReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ic   int64 `protobuf:"varint,1,opt,name=ic,proto3" json:"ic,omitempty"`
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Pref int32 `protobuf:"varint,3,opt,name=pref,proto3" json:"pref,omitempty"`
}

func (x *SetMissionPrefReq) Reset() {
	*x = SetMissionPrefReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manage_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMissionPrefReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMissionPrefReq) ProtoMessage() {}

func (x *SetMissionPrefReq) ProtoReflect() protoreflect.Message {
	mi := &file_manage_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMissionPrefReq.ProtoReflect.Descriptor instead.
func (*SetMissionPrefReq) Descriptor() ([]byte, []int) {
	return file_manage_proto_rawDescGZIP(), []int{28}
}

func (x *SetMissionPrefReq) GetIc() int64 {
	if x != nil {
		return x.Ic
	}
	return 0
}

func (x *SetMissionPrefReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SetMissionPrefReq) GetPref() int32 {
	if x != nil {
		return x.Pref
	}
	return 0
}

var File_manage_proto protoreflect.FileDescriptor

var file_manage_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6d, 0x61, 0x69, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x08, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x01, 0x73, 0x22, 0xb2, 0x02, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x12, 0x28, 0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x49, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0f, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x06,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x69, 0x6c, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x61, 0x69, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x12,
	0x2e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x76, 0x0a, 0x12, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x4d, 0x4a, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x39, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x4d, 0x4a,
	0x50, 0x52, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x2f, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57,
	0x65, 0x63, 0x68, 0x61, 0x74, 0x43, 0x44, 0x4b, 0x65, 0x79, 0x4d, 0x6a, 0x70, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x57, 0x65, 0x63,
	0x68, 0x61, 0x74, 0x43, 0x44, 0x4b, 0x65, 0x79, 0x4d, 0x6a, 0x70, 0x52, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x64, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x64, 0x4b, 0x65, 0x79, 0x22, 0x4c, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x43, 0x44, 0x4b, 0x65, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x22, 0x78, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x43, 0x44, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x70, 0x63, 0x64, 0x6b, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x43, 0x44, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x74, 0x2e, 0x50, 0x63, 0x64, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x70,
	0x63, 0x64, 0x6b, 0x1a, 0x37, 0x0a, 0x09, 0x50, 0x63, 0x64, 0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x0b,
	0x43, 0x44, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x22, 0x6e, 0x0a, 0x14, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e,
	0x64, 0x41, 0x74, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x43, 0x44, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e,
	0x64, 0x41, 0x74, 0x22, 0x85, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x4f, 0x75, 0x74, 0x50, 0x75, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x55, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x92, 0x02, 0x0a, 0x12,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x55, 0x72, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x6f,
	0x77, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x6c, 0x6f, 0x77, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x88, 0x01, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x03, 0x6f, 0x70,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x52, 0x03, 0x6f, 0x70, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x43, 0x0a, 0x11, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64,
	0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x22, 0x9a, 0x01, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x1a, 0x4d,
	0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2d, 0x0a,
	0x11, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x12,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x13, 0x41, 0x6c, 0x6c, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x41, 0x6e, 0x64, 0x57, 0x4c, 0x12,
	0x20, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x52, 0x01,
	0x76, 0x22, 0x47, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x79, 0x73, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x08, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x4a, 0x0a, 0x0e, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x43, 0x44, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6d, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x63, 0x0a, 0x15, 0x41, 0x6c, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x74, 0x53, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x22, 0x52, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x05,
	0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x41, 0x6c,
	0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x4e, 0x65, 0x77, 0x52, 0x65, 0x74,
	0x53, 0x75, 0x62, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0e, 0x46, 0x65,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x4b, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x65, 0x66, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x65,
	0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x72, 0x65, 0x66, 0x2a, 0x55, 0x0a,
	0x0c, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x12, 0x0b, 0x0a,
	0x07, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x64,
	0x64, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x43, 0x6c, 0x65, 0x61, 0x72, 0x49, 0x63, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x6c, 0x65,
	0x61, 0x72, 0x49, 0x70, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x41,
	0x6c, 0x6c, 0x10, 0x05, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_manage_proto_rawDescOnce sync.Once
	file_manage_proto_rawDescData = file_manage_proto_rawDesc
)

func file_manage_proto_rawDescGZIP() []byte {
	file_manage_proto_rawDescOnce.Do(func() {
		file_manage_proto_rawDescData = protoimpl.X.CompressGZIP(file_manage_proto_rawDescData)
	})
	return file_manage_proto_rawDescData
}

var file_manage_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_manage_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_manage_proto_goTypes = []interface{}{
	(WhiteListOpt)(0),               // 0: WhiteListOpt
	(*GenTokenResp)(nil),            // 1: GenTokenResp
	(*StringStruct)(nil),            // 2: StringStruct
	(*SendMailReq)(nil),             // 3: SendMailReq
	(*GenerateActiveCode)(nil),      // 4: GenerateActiveCode
	(*GetActiveCodeMJP)(nil),        // 5: GetActiveCodeMJP
	(*GetActiveCodeMJPRet)(nil),     // 6: GetActiveCodeMJPRet
	(*GetWechatCDKeyMjp)(nil),       // 7: GetWechatCDKeyMjp
	(*WechatCDKeyMjpRet)(nil),       // 8: WechatCDKeyMjpRet
	(*SetPublicCDKeyTime)(nil),      // 9: SetPublicCDKeyTime
	(*PublicCDKeyRet)(nil),          // 10: PublicCDKeyRet
	(*CDKeyReward)(nil),             // 11: CDKeyReward
	(*CustomizationCodeSet)(nil),    // 12: CustomizationCodeSet
	(*PersonalCDKey)(nil),           // 13: PersonalCDKey
	(*SetActorOutPutStatusReq)(nil), // 14: SetActorOutPutStatusReq
	(*VersionCheckPublic)(nil),      // 15: VersionCheckPublic
	(*ChangeWhiteList)(nil),         // 16: ChangeWhiteList
	(*PersonalGroupItem)(nil),       // 17: PersonalGroupItem
	(*PersonalGroupInfo)(nil),       // 18: PersonalGroupInfo
	(*AvailableCodesReq)(nil),       // 19: AvailableCodesReq
	(*AvailableCodesResp)(nil),      // 20: AvailableCodesResp
	(*AllVersionAddrAndWL)(nil),     // 21: AllVersionAddrAndWL
	(*GroupSysNoticeReq)(nil),       // 22: GroupSysNoticeReq
	(*Int32Req)(nil),                // 23: Int32Req
	(*ImportCDKeySet)(nil),          // 24: ImportCDKeySet
	(*GetAllPublicKeyNewReq)(nil),   // 25: GetAllPublicKeyNewReq
	(*AllPublicKeyNewRetSub)(nil),   // 26: AllPublicKeyNewRetSub
	(*AllPublicKeyNewRet)(nil),      // 27: AllPublicKeyNewRet
	(*FeedAccountReq)(nil),          // 28: FeedAccountReq
	(*SetMissionPrefReq)(nil),       // 29: SetMissionPrefReq
	nil,                             // 30: PublicCDKeyRet.PcdkEntry
	nil,                             // 31: PersonalGroupInfo.GroupsEntry
	(*ItemCommon)(nil),              // 32: ItemCommon
	(*MailContainer)(nil),           // 33: MailContainer
	(*VersionCheckMongo)(nil),       // 34: VersionCheckMongo
}
var file_manage_proto_depIdxs = []int32{
	32, // 0: SendMailReq.reward:type_name -> ItemCommon
	33, // 1: SendMailReq.containers:type_name -> MailContainer
	30, // 2: PublicCDKeyRet.pcdk:type_name -> PublicCDKeyRet.PcdkEntry
	0,  // 3: ChangeWhiteList.opt:type_name -> WhiteListOpt
	31, // 4: PersonalGroupInfo.groups:type_name -> PersonalGroupInfo.GroupsEntry
	34, // 5: AllVersionAddrAndWL.v:type_name -> VersionCheckMongo
	26, // 6: AllPublicKeyNewRet.codes:type_name -> AllPublicKeyNewRetSub
	17, // 7: PersonalGroupInfo.GroupsEntry.value:type_name -> PersonalGroupItem
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_manage_proto_init() }
func file_manage_proto_init() {
	if File_manage_proto != nil {
		return
	}
	file_game_proto_init()
	file_mail_proto_init()
	file_db_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_manage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenTokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateActiveCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveCodeMJP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveCodeMJPRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWechatCDKeyMjp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WechatCDKeyMjpRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPublicCDKeyTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicCDKeyRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CDKeyReward); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomizationCodeSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalCDKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetActorOutPutStatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionCheckPublic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeWhiteList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalGroupItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableCodesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableCodesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllVersionAddrAndWL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupSysNoticeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int32Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportCDKeySet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPublicKeyNewReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllPublicKeyNewRetSub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllPublicKeyNewRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manage_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMissionPrefReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_manage_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manage_proto_goTypes,
		DependencyIndexes: file_manage_proto_depIdxs,
		EnumInfos:         file_manage_proto_enumTypes,
		MessageInfos:      file_manage_proto_msgTypes,
	}.Build()
	File_manage_proto = out.File
	file_manage_proto_rawDesc = nil
	file_manage_proto_goTypes = nil
	file_manage_proto_depIdxs = nil
}
