// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: personality.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ModifyColorfulReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ColorfulId int32 `protobuf:"varint,1,opt,name=colorfulId,proto3" json:"colorfulId,omitempty"`
}

func (x *ModifyColorfulReq) Reset() {
	*x = ModifyColorfulReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personality_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyColorfulReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyColorfulReq) ProtoMessage() {}

func (x *ModifyColorfulReq) ProtoReflect() protoreflect.Message {
	mi := &file_personality_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyColorfulReq.ProtoReflect.Descriptor instead.
func (*ModifyColorfulReq) Descriptor() ([]byte, []int) {
	return file_personality_proto_rawDescGZIP(), []int{0}
}

func (x *ModifyColorfulReq) GetColorfulId() int32 {
	if x != nil {
		return x.ColorfulId
	}
	return 0
}

type ModifyTitleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TitleId int32 `protobuf:"varint,1,opt,name=titleId,proto3" json:"titleId,omitempty"`
}

func (x *ModifyTitleReq) Reset() {
	*x = ModifyTitleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personality_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyTitleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyTitleReq) ProtoMessage() {}

func (x *ModifyTitleReq) ProtoReflect() protoreflect.Message {
	mi := &file_personality_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyTitleReq.ProtoReflect.Descriptor instead.
func (*ModifyTitleReq) Descriptor() ([]byte, []int) {
	return file_personality_proto_rawDescGZIP(), []int{1}
}

func (x *ModifyTitleReq) GetTitleId() int32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

type ModifyAvatarFrameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarFrameId int32 `protobuf:"varint,1,opt,name=avatarFrameId,proto3" json:"avatarFrameId,omitempty"`
}

func (x *ModifyAvatarFrameReq) Reset() {
	*x = ModifyAvatarFrameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personality_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyAvatarFrameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyAvatarFrameReq) ProtoMessage() {}

func (x *ModifyAvatarFrameReq) ProtoReflect() protoreflect.Message {
	mi := &file_personality_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyAvatarFrameReq.ProtoReflect.Descriptor instead.
func (*ModifyAvatarFrameReq) Descriptor() ([]byte, []int) {
	return file_personality_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyAvatarFrameReq) GetAvatarFrameId() int32 {
	if x != nil {
		return x.AvatarFrameId
	}
	return 0
}

type PersonalityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarList      []int32         `protobuf:"varint,1,rep,packed,name=avatarList,proto3" json:"avatarList,omitempty"`                                                                                             // 头像列表
	AvatarFrameList []int32         `protobuf:"varint,2,rep,packed,name=avatarFrameList,proto3" json:"avatarFrameList,omitempty"`                                                                                   // 头像框列表
	TitleList       []int32         `protobuf:"varint,3,rep,packed,name=titleList,proto3" json:"titleList,omitempty"`                                                                                               // 称号列表
	ColorfulNameMap map[int32]int32 `protobuf:"bytes,4,rep,name=colorfulNameMap,proto3" json:"colorfulNameMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 炫彩名<id,剩余时间秒(-1表示不限时)>
}

func (x *PersonalityInfo) Reset() {
	*x = PersonalityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personality_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalityInfo) ProtoMessage() {}

func (x *PersonalityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_personality_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalityInfo.ProtoReflect.Descriptor instead.
func (*PersonalityInfo) Descriptor() ([]byte, []int) {
	return file_personality_proto_rawDescGZIP(), []int{3}
}

func (x *PersonalityInfo) GetAvatarList() []int32 {
	if x != nil {
		return x.AvatarList
	}
	return nil
}

func (x *PersonalityInfo) GetAvatarFrameList() []int32 {
	if x != nil {
		return x.AvatarFrameList
	}
	return nil
}

func (x *PersonalityInfo) GetTitleList() []int32 {
	if x != nil {
		return x.TitleList
	}
	return nil
}

func (x *PersonalityInfo) GetColorfulNameMap() map[int32]int32 {
	if x != nil {
		return x.ColorfulNameMap
	}
	return nil
}

var File_personality_proto protoreflect.FileDescriptor

var file_personality_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6c,
	0x6f, 0x72, 0x66, 0x75, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6f,
	0x72, 0x66, 0x75, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x66, 0x75, 0x6c, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x14, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x22, 0x8e, 0x02, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x69,
	0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x0f, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4f,
	0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x66, 0x75, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x4d, 0x61,
	0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x66,
	0x75, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x66, 0x75, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x4d, 0x61, 0x70, 0x1a,
	0x42, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x66, 0x75, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x4d,
	0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_personality_proto_rawDescOnce sync.Once
	file_personality_proto_rawDescData = file_personality_proto_rawDesc
)

func file_personality_proto_rawDescGZIP() []byte {
	file_personality_proto_rawDescOnce.Do(func() {
		file_personality_proto_rawDescData = protoimpl.X.CompressGZIP(file_personality_proto_rawDescData)
	})
	return file_personality_proto_rawDescData
}

var file_personality_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_personality_proto_goTypes = []interface{}{
	(*ModifyColorfulReq)(nil),    // 0: ModifyColorfulReq
	(*ModifyTitleReq)(nil),       // 1: ModifyTitleReq
	(*ModifyAvatarFrameReq)(nil), // 2: ModifyAvatarFrameReq
	(*PersonalityInfo)(nil),      // 3: PersonalityInfo
	nil,                          // 4: PersonalityInfo.ColorfulNameMapEntry
}
var file_personality_proto_depIdxs = []int32{
	4, // 0: PersonalityInfo.colorfulNameMap:type_name -> PersonalityInfo.ColorfulNameMapEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_personality_proto_init() }
func file_personality_proto_init() {
	if File_personality_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_personality_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyColorfulReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personality_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyTitleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personality_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyAvatarFrameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personality_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personality_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_personality_proto_goTypes,
		DependencyIndexes: file_personality_proto_depIdxs,
		MessageInfos:      file_personality_proto_msgTypes,
	}.Build()
	File_personality_proto = out.File
	file_personality_proto_rawDesc = nil
	file_personality_proto_goTypes = nil
	file_personality_proto_depIdxs = nil
}
