// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: real_name.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RealNameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRealnamed   bool  `protobuf:"varint,1,opt,name=isRealnamed,proto3" json:"isRealnamed,omitempty"`
	IsAdult       bool  `protobuf:"varint,2,opt,name=isAdult,proto3" json:"isAdult,omitempty"`
	AlreadyReward bool  `protobuf:"varint,3,opt,name=alreadyReward,proto3" json:"alreadyReward,omitempty"`
	HasBind       bool  `protobuf:"varint,4,opt,name=hasBind,proto3" json:"hasBind,omitempty"`
	Age           int32 `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *RealNameInfo) Reset() {
	*x = RealNameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_real_name_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameInfo) ProtoMessage() {}

func (x *RealNameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_real_name_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameInfo.ProtoReflect.Descriptor instead.
func (*RealNameInfo) Descriptor() ([]byte, []int) {
	return file_real_name_proto_rawDescGZIP(), []int{0}
}

func (x *RealNameInfo) GetIsRealnamed() bool {
	if x != nil {
		return x.IsRealnamed
	}
	return false
}

func (x *RealNameInfo) GetIsAdult() bool {
	if x != nil {
		return x.IsAdult
	}
	return false
}

func (x *RealNameInfo) GetAlreadyReward() bool {
	if x != nil {
		return x.AlreadyReward
	}
	return false
}

func (x *RealNameInfo) GetHasBind() bool {
	if x != nil {
		return x.HasBind
	}
	return false
}

func (x *RealNameInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type RealNameRewardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info             *RealNameInfo     `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	ItemUpdateResult *ItemUpdateResult `protobuf:"bytes,2,opt,name=itemUpdateResult,proto3" json:"itemUpdateResult,omitempty"`
}

func (x *RealNameRewardResp) Reset() {
	*x = RealNameRewardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_real_name_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameRewardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameRewardResp) ProtoMessage() {}

func (x *RealNameRewardResp) ProtoReflect() protoreflect.Message {
	mi := &file_real_name_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameRewardResp.ProtoReflect.Descriptor instead.
func (*RealNameRewardResp) Descriptor() ([]byte, []int) {
	return file_real_name_proto_rawDescGZIP(), []int{1}
}

func (x *RealNameRewardResp) GetInfo() *RealNameInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *RealNameRewardResp) GetItemUpdateResult() *ItemUpdateResult {
	if x != nil {
		return x.ItemUpdateResult
	}
	return nil
}

type RealNameQueryRedirectRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FreeDay bool   `protobuf:"varint,2,opt,name=free_day,json=freeDay,proto3" json:"free_day,omitempty"`
	IdCard  string `protobuf:"bytes,3,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	Ts      int64  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *RealNameQueryRedirectRet) Reset() {
	*x = RealNameQueryRedirectRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_real_name_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameQueryRedirectRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameQueryRedirectRet) ProtoMessage() {}

func (x *RealNameQueryRedirectRet) ProtoReflect() protoreflect.Message {
	mi := &file_real_name_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameQueryRedirectRet.ProtoReflect.Descriptor instead.
func (*RealNameQueryRedirectRet) Descriptor() ([]byte, []int) {
	return file_real_name_proto_rawDescGZIP(), []int{2}
}

func (x *RealNameQueryRedirectRet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RealNameQueryRedirectRet) GetFreeDay() bool {
	if x != nil {
		return x.FreeDay
	}
	return false
}

func (x *RealNameQueryRedirectRet) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *RealNameQueryRedirectRet) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type RealNameQueryRedirectGoRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FreeDay bool   `protobuf:"varint,2,opt,name=freeDay,proto3" json:"freeDay,omitempty"`
	IdCard  string `protobuf:"bytes,3,opt,name=idCard,proto3" json:"idCard,omitempty"`
	Ts      int64  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *RealNameQueryRedirectGoRet) Reset() {
	*x = RealNameQueryRedirectGoRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_real_name_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameQueryRedirectGoRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameQueryRedirectGoRet) ProtoMessage() {}

func (x *RealNameQueryRedirectGoRet) ProtoReflect() protoreflect.Message {
	mi := &file_real_name_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameQueryRedirectGoRet.ProtoReflect.Descriptor instead.
func (*RealNameQueryRedirectGoRet) Descriptor() ([]byte, []int) {
	return file_real_name_proto_rawDescGZIP(), []int{3}
}

func (x *RealNameQueryRedirectGoRet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RealNameQueryRedirectGoRet) GetFreeDay() bool {
	if x != nil {
		return x.FreeDay
	}
	return false
}

func (x *RealNameQueryRedirectGoRet) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *RealNameQueryRedirectGoRet) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type RealNameCheckRedirect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid  string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RealNameCheckRedirect) Reset() {
	*x = RealNameCheckRedirect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_real_name_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameCheckRedirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameCheckRedirect) ProtoMessage() {}

func (x *RealNameCheckRedirect) ProtoReflect() protoreflect.Message {
	mi := &file_real_name_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameCheckRedirect.ProtoReflect.Descriptor instead.
func (*RealNameCheckRedirect) Descriptor() ([]byte, []int) {
	return file_real_name_proto_rawDescGZIP(), []int{4}
}

func (x *RealNameCheckRedirect) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *RealNameCheckRedirect) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RealNameCheckRedirectRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Code    int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RealNameCheckRedirectRet) Reset() {
	*x = RealNameCheckRedirectRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_real_name_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealNameCheckRedirectRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameCheckRedirectRet) ProtoMessage() {}

func (x *RealNameCheckRedirectRet) ProtoReflect() protoreflect.Message {
	mi := &file_real_name_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameCheckRedirectRet.ProtoReflect.Descriptor instead.
func (*RealNameCheckRedirectRet) Descriptor() ([]byte, []int) {
	return file_real_name_proto_rawDescGZIP(), []int{5}
}

func (x *RealNameCheckRedirectRet) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RealNameCheckRedirectRet) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RealNameCheckRedirectRet) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_real_name_proto protoreflect.FileDescriptor

var file_real_name_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x01,
	0x0a, 0x0c, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20,
	0x0a, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x61, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x52, 0x65, 0x61, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x41, 0x64, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x64, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x6c,
	0x72, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0d, 0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x42, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x42, 0x69, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x76, 0x0a, 0x12,
	0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x21, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x10, 0x69, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x10, 0x69, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x76, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65,
	0x5f, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65,
	0x44, 0x61, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0x76, 0x0a, 0x1a,
	0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x47, 0x6f, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x65, 0x65, 0x44, 0x61, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x44, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x74, 0x73, 0x22, 0x3d, 0x0a, 0x15, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x60, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_real_name_proto_rawDescOnce sync.Once
	file_real_name_proto_rawDescData = file_real_name_proto_rawDesc
)

func file_real_name_proto_rawDescGZIP() []byte {
	file_real_name_proto_rawDescOnce.Do(func() {
		file_real_name_proto_rawDescData = protoimpl.X.CompressGZIP(file_real_name_proto_rawDescData)
	})
	return file_real_name_proto_rawDescData
}

var file_real_name_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_real_name_proto_goTypes = []interface{}{
	(*RealNameInfo)(nil),               // 0: RealNameInfo
	(*RealNameRewardResp)(nil),         // 1: RealNameRewardResp
	(*RealNameQueryRedirectRet)(nil),   // 2: RealNameQueryRedirectRet
	(*RealNameQueryRedirectGoRet)(nil), // 3: RealNameQueryRedirectGoRet
	(*RealNameCheckRedirect)(nil),      // 4: RealNameCheckRedirect
	(*RealNameCheckRedirectRet)(nil),   // 5: RealNameCheckRedirectRet
	(*ItemUpdateResult)(nil),           // 6: ItemUpdateResult
}
var file_real_name_proto_depIdxs = []int32{
	0, // 0: RealNameRewardResp.info:type_name -> RealNameInfo
	6, // 1: RealNameRewardResp.itemUpdateResult:type_name -> ItemUpdateResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_real_name_proto_init() }
func file_real_name_proto_init() {
	if File_real_name_proto != nil {
		return
	}
	file_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_real_name_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_real_name_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameRewardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_real_name_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameQueryRedirectRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_real_name_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameQueryRedirectGoRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_real_name_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameCheckRedirect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_real_name_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealNameCheckRedirectRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_real_name_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_real_name_proto_goTypes,
		DependencyIndexes: file_real_name_proto_depIdxs,
		MessageInfos:      file_real_name_proto_msgTypes,
	}.Build()
	File_real_name_proto = out.File
	file_real_name_proto_rawDesc = nil
	file_real_name_proto_goTypes = nil
	file_real_name_proto_depIdxs = nil
}
