// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.0
// source: sign_in_7_day.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 玩家七日签到信息
type SignIn7DayInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanSignIn bool  `protobuf:"varint,1,opt,name=CanSignIn,proto3" json:"CanSignIn,omitempty"` // 当天是否可签到
	SignInDay int32 `protobuf:"varint,2,opt,name=SignInDay,proto3" json:"SignInDay,omitempty"` // 签到第几天了，初始为0
}

func (x *SignIn7DayInfo) Reset() {
	*x = SignIn7DayInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_in_7_day_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn7DayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn7DayInfo) ProtoMessage() {}

func (x *SignIn7DayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sign_in_7_day_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn7DayInfo.ProtoReflect.Descriptor instead.
func (*SignIn7DayInfo) Descriptor() ([]byte, []int) {
	return file_sign_in_7_day_proto_rawDescGZIP(), []int{0}
}

func (x *SignIn7DayInfo) GetCanSignIn() bool {
	if x != nil {
		return x.CanSignIn
	}
	return false
}

func (x *SignIn7DayInfo) GetSignInDay() int32 {
	if x != nil {
		return x.SignInDay
	}
	return 0
}

// 七日签到，签到返回
type SingIn7DeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *SignIn7DayInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Item *ItemUpdateResult `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"` // 签到奖励
}

func (x *SingIn7DeyResp) Reset() {
	*x = SingIn7DeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_in_7_day_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingIn7DeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingIn7DeyResp) ProtoMessage() {}

func (x *SingIn7DeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_sign_in_7_day_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingIn7DeyResp.ProtoReflect.Descriptor instead.
func (*SingIn7DeyResp) Descriptor() ([]byte, []int) {
	return file_sign_in_7_day_proto_rawDescGZIP(), []int{1}
}

func (x *SingIn7DeyResp) GetInfo() *SignIn7DayInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SingIn7DeyResp) GetItem() *ItemUpdateResult {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_sign_in_7_day_proto protoreflect.FileDescriptor

var file_sign_in_7_day_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x5f, 0x37, 0x5f, 0x64, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4c, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x37, 0x44, 0x61, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x49,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x44, 0x61, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x44, 0x61, 0x79, 0x22,
	0x5c, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x37, 0x44, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x37, 0x44, 0x61, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x42, 0x0b, 0x5a,
	0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sign_in_7_day_proto_rawDescOnce sync.Once
	file_sign_in_7_day_proto_rawDescData = file_sign_in_7_day_proto_rawDesc
)

func file_sign_in_7_day_proto_rawDescGZIP() []byte {
	file_sign_in_7_day_proto_rawDescOnce.Do(func() {
		file_sign_in_7_day_proto_rawDescData = protoimpl.X.CompressGZIP(file_sign_in_7_day_proto_rawDescData)
	})
	return file_sign_in_7_day_proto_rawDescData
}

var file_sign_in_7_day_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sign_in_7_day_proto_goTypes = []interface{}{
	(*SignIn7DayInfo)(nil),   // 0: SignIn7DayInfo
	(*SingIn7DeyResp)(nil),   // 1: SingIn7DeyResp
	(*ItemUpdateResult)(nil), // 2: ItemUpdateResult
}
var file_sign_in_7_day_proto_depIdxs = []int32{
	0, // 0: SingIn7DeyResp.info:type_name -> SignIn7DayInfo
	2, // 1: SingIn7DeyResp.item:type_name -> ItemUpdateResult
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sign_in_7_day_proto_init() }
func file_sign_in_7_day_proto_init() {
	if File_sign_in_7_day_proto != nil {
		return
	}
	file_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sign_in_7_day_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignIn7DayInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_in_7_day_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingIn7DeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sign_in_7_day_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sign_in_7_day_proto_goTypes,
		DependencyIndexes: file_sign_in_7_day_proto_depIdxs,
		MessageInfos:      file_sign_in_7_day_proto_msgTypes,
	}.Build()
	File_sign_in_7_day_proto = out.File
	file_sign_in_7_day_proto_rawDesc = nil
	file_sign_in_7_day_proto_goTypes = nil
	file_sign_in_7_day_proto_depIdxs = nil
}
